version: "2"

services:
  handbrake:
    container_name: handbrake 
    hostname: handbrake
    image: coppit/handbrake
    ports:
      - "8079:8080"
    cap_add:
      - SYS_NICE
    volumes:
      - "/home/quentin/.config/handbrake:/config"
      - "/mnt/vault/media/video/:/media"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  openvpn:
    container_name: openvpn
    hostname: openvpn
    image: kylemanna/openvpn
    ports:
      - "53:1194/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - "/home/quentin/.config/openvpn:/etc/openvpn"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"


  influxdb:
    container_name: influxdb
    hostname: influxdb
    image: influxdb
#    user: "1000"
    ports:
      - "8078:8078"
    volumes:
      - "/home/quentin/.config/influxdb/conf:/etc/influxdb"
      - "/home/quentin/.config/influxdb/db:/var/lib/influxdb"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  grafana:
    container_name: grafana
    hostname: grafana
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    volumes:
      - "/home/quentin/.config/grafana/conf:/etc/grafana"
      - "/home/quentin/.config/grafana/db:/var/lib/grafana"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx
    ports:
      - "21098:21098"
      - "21096:21096"
    volumes:
      - "/home/quentin/.config/nginx/conf:/etc/nginx"
      - "/mnt/vault/media/video/torrents:/www/torrents:ro"
      - "/var/log/nginx/:/var/log/nginx/"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  nodered:
    container_name: nodered
    hostname: nodered
    image: "nodered/node-red-docker"
    user: "1000"
    ports:
      - "1880:1880"
    volumes:
      - "/home/quentin/.config/nodered/data:/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    
  openhab:
    container_name: openhab
    hostname: openhab
    image: "openhab/openhab:2.1.0-amd64"
    privileged: true
    ports:
      - "8081:8081" #Web interface
    devices:
      - "/dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1R14P3-if00-port0"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/home/quentin/.config/openhab/addons:/openhab/addons"
      - "/home/quentin/.config/openhab/conf:/openhab/conf"
      - "/home/quentin/.config/openhab/userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8081"
      OPENHAB_HTTPS_PORT: "8443"
      USER_ID: "1000"
      GROUP_ID: "1000"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  mosquitto:
    container_name: mosquitto
    hostname: mosquitto
    image: qpeten/docker-mosquitto
#    build: ../mosquitto
    ports:
      - "1883:1883"
    volumes:
      - /home/quentin/.config/mosquito:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  movieSync-master:
    container_name: movieSync-master
    hostname: movieSync-master
    image: qpeten/docker-moviesync-master
    ports:
      - "51012:51012"
      - "9094:9091"
    volumes:
      - /home/quentin/.config/movieSync-master/transmission/:/transmission-config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/vault/media/video/movies/:/movies:ro
      - /mnt/vault/media/video/torrents:/torrents
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
      
  dhcpd:
    container_name: dhcpd
    hostname: dhcpd
    image: sirferdek/isc-dhcp-server
    network_mode: host
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - /home/quentin/.config/dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf
       - /home/quentin/.config/dhcp/lib:/var/lib/dhcp
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: always
  
  fileServer-welcome:
    container_name: fileServer-welcome
    hostname: fileServer-welcome
    image: qpeten/docker-fileserverwelcome
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: always

#  couchpotato:
#    container_name: couchpotato
#    hostname: couchpotato
#    image: linuxserver/couchpotato
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /home/quentin/couchpotato/config:/config
#      - /mnt/vault/media/video/download:/downloads
#      - /mnt/vault/media/video/movies:/movies:ro
#    environment:
#      - PGID=1000
#      - PUID=1000
#      - TZ=Europe/Brussels
#    ports:
#      - "5050:5050"
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "1m"
#        max-file: "1"
#    restart: always


  transmission-quentin:
    container_name: transmission-quentin
    hostname: transmission-quentin
    image: linuxserver/transmission
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/vault/documents/quentin/tmp/download/.config:/config
      - /mnt/vault/documents/quentin/tmp/download:/downloads
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - "9091:9091"
      - "51016:51016"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: always


  transmission-auto:
    container_name: transmission-auto
    hostname: transmission-auto
    image: linuxserver/transmission
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/vault/media/video/download/.config:/config
      - /mnt/vault/media/video/download/.dlfini:/downloads
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - "9093:9091"
      - "51414:51413"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: always


  transmission-bruno:
    container_name: transmission-bruno
    hostname: transmission-bruno
    image: linuxserver/transmission
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/vault/documents/parents/Bruno/Transmission/.config:/config
      - /mnt/vault/documents/parents/Bruno/Transmission:/downloads
    environment:
      - PGID=1002
      - PUID=1002
    ports:
      - "9092:9091"
      - "51413:51413"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: always
