version: "2"

services:
  mosquitto:
    container_name: mosquitto
    hostname: mosquitto
    image: qpeten/docker-mosquitto
#    build: ../mosquitto
    ports:
      - "1883:1883"
    volumes:
      - /home/quentin/.config/mosquito:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  movieSync-master:
    container_name: movieSync-master
    hostname: movieSync-master
    image: qpeten/docker-moviesync-master
    ports:
      - "51012:51012"
      - "9094:9091"
    volumes:
      - /home/quentin/.config/movieSync-master/transmission/:/transmission-config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/vault/media/video/movies/:/movies:ro
      - /mnt/vault/media/video/torrents:/torrents
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
      
  dhcpd:
    container_name: dhcpd
    hostname: dhcpd
    image: sirferdek/isc-dhcp-server
    network_mode: host
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - /home/quentin/.config/dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf
       - /home/quentin/.config/dhcp/lib:/var/lib/dhcp
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: always
  
  fileServer-welcome:
    container_name: fileServer-welcome
    hostname: fileServer-welcome
    image: qpeten/docker-fileserverwelcome
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: always

  domoticz:
    container_name: domoticz
    hostname: domoticz
    image: qpeten/docker-domoticz
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/quentin/.config/domoticz:/config:rw
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "100"
    restart: always

  syncthing:
    container_name: syncthing
    hostname: syncthing
    image: qpeten/docker-syncthing
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/vault/:/mnt/tank:rw
      - /home/quentin/.config/syncthing:/config:rw
    network_mode: "host"
    ports:
      - "22000:22000"
      - "8384:8384"
      - "21027:21027/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: always
  
  
  couchpotato:
    container_name: couchpotato
    hostname: couchpotato
    image: linuxserver/couchpotato
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/quentin/couchpotato/config:/config
      - /mnt/vault/media/video/download:/downloads
      - /mnt/vault/media/video/movies:/movies:ro
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Brussels
    ports:
      - "5050:5050"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: always


  transmission-quentin:
    container_name: transmission-quentin
    hostname: transmission-quentin
    image: linuxserver/transmission
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/vault/documents/quentin/tmp/download/.config:/config
      - /mnt/vault/documents/quentin/tmp/download:/downloads
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - "9091:9091"
      - "51016:51016"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: always


  transmission-auto:
    container_name: transmission-auto
    hostname: transmission-auto
    image: linuxserver/transmission
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/vault/media/video/download/.config:/config
      - /mnt/vault/media/video/download/.dlfini:/downloads
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - "9093:9091"
      - "51414:51413"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: always


  transmission-bruno:
    container_name: transmission-bruno
    hostname: transmission-bruno
    image: linuxserver/transmission
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/vault/documents/parents/Bruno/Transmission/.config:/config
      - /mnt/vault/documents/parents/Bruno/Transmission:/downloads
    environment:
      - PGID=1002
      - PUID=1002
    ports:
      - "9092:9091"
      - "51413:51413"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: always
