version: "2"

services:
  #Used by graylog
  mongodb:
    container_name: graylog_mongodb
    hostname: graylog_mongodb
    image: mongo:3
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/db

  #Used by graylog
  elasticsearch:
    container_name: graylog_elasticsearch
    hostname: graylog_eslasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g

  graylog:
    container_name: graylog
    hostname : graylog
    image: graylog/graylog:latest
    volumes:
      - /home/quentin/.config/graylog/journal/:/usr/share/graylog/data/journal
      - /home/quentin/.config/graylog/config/:/usr/share/graylog/data/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    ports:
      # Graylog web interface and REST API
      - "9000:9000"
      # fileServer	docker	dhcp
      - "51400:51400"
      # fileServer	docker	movieSync-master
      - "51401:51401"
      # fileServer	rsyslog
      - "51402:51402"
      # fileServer	docker	transmission-quentin
      - "51403:51403"
      # fileServer	docker	transmission-bruno
      - "51404:51404"
      # fileServer	docker	transmission-auto
      - "51405:51405"
      # fileServer	docker	fileServer-welcome
      - "51406:51406"
      # fileServer	docker	domoticz
      - "51407:51407"
      # fileServer	docker	couchpotato
      - "51408:51408"
      # fileServer	docker	syncthing
      - "51409:51409"
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  movieSync-master:
    container_name: movieSync-master
    hostname: movieSync-master
    image: qpeten/docker-moviesync-master
    ports:
      - "51012:51012"
      - "9094:9091"
    volumes:
      - /home/quentin/.config/movieSync-master/transmission/:/transmission-config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/vault/media/video/movies/:/movies:ro
      - /mnt/vault/media/video/torrents:/torrents
    restart: always
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://192.168.1.150:51401"                   
      
  dhcpd:
    container_name: dhcpd
    hostname: dhcpd
    image: sirferdek/isc-dhcp-server
    network_mode: host
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - /home/quentin/.config/dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf
       - /home/quentin/.config/dhcp/lib:/var/lib/dhcp
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://192.168.1.150:51400"
    restart: always
  
  fileServer-welcome:
    container_name: fileServer-welcome
    hostname: fileServer-welcome
    image: qpeten/docker-fileserverwelcome
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://192.168.1.150:51406"
    restart: always

  domoticz:
    container_name: domoticz
    hostname: domoticz
    image: qpeten/docker-domoticz
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/quentin/.config/domoticz:/config:rw
    ports:
      - "8080:8080"
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://192.168.1.150:51407"
    restart: always

  syncthing:
    container_name: syncthing
    hostname: syncthing
    image: qpeten/docker-syncthing
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/vault/:/mnt/tank:rw
      - /home/quentin/.config/syncthing:/config:rw
    network_mode: "host"
    ports:
      - "22000:22000"
      - "8384:8384"
      - "21027:21027/udp"
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://192.168.1.150:51409"
    restart: always
  
  
  couchpotato:
    container_name: couchpotato
    hostname: couchpotato
    image: linuxserver/couchpotato
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/quentin/couchpotato/config:/config
      - /mnt/vault/media/video/download:/downloads
      - /mnt/vault/media/video/movies:/movies:ro
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Brussels
    ports:
      - "5050:5050"
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://192.168.1.150:51408"
    restart: always


  transmission-quentin:
    container_name: transmission-quentin
    hostname: transmission-quentin
    image: linuxserver/transmission
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/vault/documents/quentin/tmp/download/.config:/config
      - /mnt/vault/documents/quentin/tmp/download:/downloads
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - "9091:9091"
      - "51016:51016"
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://192.168.1.150:51403"
    restart: always


  transmission-auto:
    container_name: transmission-auto
    hostname: transmission-auto
    image: linuxserver/transmission
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/vault/media/video/download/.config:/config
      - /mnt/vault/media/video/download/.dlfini:/downloads
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - "9093:9091"
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://192.168.1.150:51405"
    restart: always


  transmission-bruno:
    container_name: transmission-bruno
    hostname: transmission-bruno
    image: linuxserver/transmission
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/vault/documents/parents/Bruno/Transmission/.config:/config
      - /mnt/vault/documents/parents/Bruno/Transmission:/downloads
    environment:
      - PGID=1002
      - PUID=1002
    ports:
      - "9092:9091"
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://192.168.1.150:51404"
    restart: always
